apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: pokedex
data:
  DATABASE_URL: "postgresql://postgres:postgres123@postgres:5432/pokedex"
  DIRECT_URL: "postgresql://postgres:postgres123@postgres:5432/pokedex"
  REDIS_URL: "redis://redis:6379"
  NODE_ENV: "production"
  PORT: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pokedex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pokedex-voltron-backend:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: backend-config
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pokedex
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP