apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: pokedex-app

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: pokedex
  app.kubernetes.io/version: "1.0"
  app.kubernetes.io/component: app

namespace: pokedex