name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production
    needs: [lint-and-type-check, unit-tests, test]

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Clone repository if it doesn't exist
            if [ ! -d "~/pokedex-voltron" ]; then
              echo "Cloning repository..."
              git clone https://github.com/${{ github.repository }}.git ~/pokedex-voltron
            fi

            # Navigate and update
            cd ~/pokedex-voltron
            git pull origin main

            # Deploy with docker-compose
            docker-compose down || true
            docker-compose up -d --build

            # Clean up
            docker system prune -f