name: E2E test with Playwright

on:
  push:
    branches: [ main ]
    paths:
      - 'pokedex-frontend/**'
      - 'pokedex-backend/**'
      - 'e2e/**'
      - '.github/workflows/e2e-test.yml'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'pokedex-frontend/**'
      - 'pokedex-backend/**'
      - 'e2e/**'
      - '.github/workflows/e2e-test.yml'
      - '.github/workflows/deploy.yml'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pokedex_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.38
    - name: Install dependencies for e2e tests
      working-directory: ./e2e
      run: bun install --frozen-lockfile
    - name: Install dependencies for frontend
      working-directory: ./pokedex-frontend
      run: bun install --frozen-lockfile
    - name: Install dependencies for backend
      working-directory: ./pokedex-backend
      run: bun install --frozen-lockfile
    - name: Setup test database
      working-directory: ./pokedex-backend
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/pokedex_test
        DIRECT_URL: postgresql://postgres:postgres@localhost:5432/pokedex_test
      run: |
        npx prisma migrate deploy
        npx prisma generate
    - name: Install Playwright Browsers
      working-directory: ./e2e
      run: bunx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./e2e
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/pokedex_test
        DIRECT_URL: postgresql://postgres:postgres@localhost:5432/pokedex_test
      run: bun run test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: e2e/playwright-report/
        retention-days: 30
