name: Lint and Typecheck

on:
  push:
    branches: [ main ]
    paths:
      - 'pokedex-frontend/**'
      - 'pokedex-backend/**'
      - '.github/workflows/lint-and-typecheck.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'pokedex-frontend/**'
      - 'pokedex-backend/**'
      - '.github/workflows/lint-and-typecheck.yml'

jobs:
  lint-and-type-check:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        project: [frontend, backend]

    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.38

    - name: Install dependencies
      working-directory: ./pokedex-${{ matrix.project }}
      run: bun install --frozen-lockfile

    - name: Run linting
      working-directory: ./pokedex-${{ matrix.project }}
      run: bun lint

    - name: Run typescript checking
      working-directory: ./pokedex-${{ matrix.project }}
      run: bun typecheck
