name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.38
    - name: Install dependencies for e2e tests
      working-directory: ./e2e
      run: bun install --frozen-lockfile
    - name: Install dependencies for frontend
      working-directory: ./pokedex-frontend
      run: bun install --frozen-lockfile
    - name: Install dependencies for backend
      working-directory: ./pokedex-backend
      run: bun install --frozen-lockfile
    - name: Install Playwright Browsers
      working-directory: ./e2e
      run: bunx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./e2e
      run: bun run test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: e2e/playwright-report/
        retention-days: 30
